version: "3.9"

services:
  gpa_db:
    image: "postgres"
    restart: always
    container_name: gpa_db
    ports:
      - "5432:5432"
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  web_api:
    build: ./web-api
    container_name: web-api
    restart: always
    environment:
      - APP_NAME=web_api
      - ENV=Production
    env_file:
      - .env
    ports:
      - "5008:5008"
    links:
      - gpa_db
    depends_on:
      - gpa_db

  gpa_client:
    build: ./gpa-client
    container_name: gpa_client
    restart: always
    environment:
      - APP_NAME=gpa_client
    ports:
      - "8080:8080"
    links:
      - web_api
    depends_on:
      - web_api
