"""v8

Revision ID: 29f65aef48e0
Revises: 6ed97cb131ca
Create Date: 2022-04-07 16:24:12.088169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f65aef48e0'
down_revision = '6ed97cb131ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('occurred_at', sa.DateTime(timezone=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'occurred_at')
    # ### end Alembic commands ###
