"""v7

Revision ID: 6ed97cb131ca
Revises: 8096765481cc
Create Date: 2022-04-07 16:23:48.312868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed97cb131ca'
down_revision = '8096765481cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'occurred_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('occurred_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
