"""v6

Revision ID: 8096765481cc
Revises: 54426616bcb0
Create Date: 2022-04-07 16:18:01.052158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8096765481cc'
down_revision = '54426616bcb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'occurred_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'occurred_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
