"""corrects account_id column@transaction

Revision ID: be38d58c334d
Revises: c62256879791
Create Date: 2022-04-05 11:18:46.668139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be38d58c334d'
down_revision = 'c62256879791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'account_id')
    # ### end Alembic commands ###
