"""upgrade models

Revision ID: c62256879791
Revises: 9966405a0e97
Create Date: 2022-04-05 11:10:18.084484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62256879791'
down_revision = '9966405a0e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'performed_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'performed_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
